### ISSUE TITLE
Could it be used for various dashcam/roads?

### ISSUE THREAD

**Issue by mchrbn** [SharifElfouly/vehicle-speed-estimation#1]
Hey, very cool project! I'm not that familiar with NN so my question might be stupid:

I tried to use the provided trained model (b0.pth) with my own dataset that I generated from my dashcam's video using your [optical flow script](https://github.com/SharifElfouly/opical-flow-estimation-with-RAFT) - the optical flow generation works very well. However the predicted speed outputed by the 'inference script' are not accurate at all. Is this model able to work with various dashcam's video? Or only for the same video as it was trained with?

Maybe one of the issue from my side is that I didn't extracted the images from my video at the same frame interval as you?

**Comment by shafu0x** [comment]
Thank you! Not a stupid question at all. 

It definitely depends on the video you are using. You can find the videos that I used for training [here](https://github.com/commaai/speedchallenge/tree/master/data). 

You always have the opportunity to train a model yourself. You can find an example in  [`train.ipynb`](https://github.com/SharifElfouly/vehicle-speed-estimation/blob/master/train.ipynb). If you can generate the data, its quite easy actually.

**Comment by mchrbn** [comment]
Thanks for your answer!

I'm trying to re-train the network as you suggested however I was wondering if your training script is also saving the trained model or I have to add that part?

**Comment by shafu0x** [comment]
You would need to add a little bit of code in train.ipynb
